services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./build:/app/build
      - ./package.json:/app/package.json
      - ./server.js:/app/server.js
    env_file:
      - .env.development
    environment:
      - CHOKIDAR_USEPOLLING=true
